export const GET_ALL_POKEMON = 'GET_ALL_POKEMON';
export const GET_ALL_POKEMON_SUCCESS = 'GET_ALL_POKEMON_SUCCESS';
export const GET_ALL_POKEMON_FAIL = 'GET_ALL_POKEMON_FAIL';
export const GET_DETAIL_POKEMON = 'GET_DETAIL_POKEMON';
export const GET_DETAIL_POKEMON_SUCCESS = 'GET_DETAIL_POKEMON_SUCCESS';
export const GET_DETAIL_POKEMON_FAIL = 'GET_DETAIL_POKEMON_FAIL';
